In [1]:
from sklearn import preprocessing
import os
import librosa
from data_models.dataset2 import BirdDataset
import numpy as np

c:\Users\firef\Downloads\BirdsSong-master\BirdsSong-master\src\data_models\dataset2.py:50: UserWarning: PySoundFile failed. Trying audioread instead.
  wav, sr = librosa.load(path_audio, offset=offset, duration = 1.0)
C:\Users\firef\AppData\Roaming\Python\Python39\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


NoBackendError: 

In [180]:
dataset.metadata.items()

dict_items([('species', ['Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arun

In [174]:
s=dataset[5701]

print(s)

{'species': 'Tachybaptus ruficollis', 'species_encoded': 19, 'audio': array([-0.00363688,  0.00089291,  0.00938779, ...,  0.0311252 ,
       -0.01191721, -0.0797343 ], dtype=float32), 'spectrogram': array([[-20.23129 , -22.523497, -34.74211 , ..., -36.153778, -28.631557,
        -20.23129 ],
       [-20.216858, -22.552513, -36.475227, ..., -36.464546, -28.603828,
        -20.216858],
       [-20.186378, -22.474483, -34.76468 , ..., -36.039272, -28.52197 ,
        -20.186378],
       ...,
       [-21.346306, -23.656876, -36.499725, ..., -48.630013, -42.98922 ,
        -21.346306],
       [-21.36101 , -23.672108, -36.576813, ..., -50.89184 , -43.0451  ,
        -21.36101 ],
       [-21.366138, -23.67694 , -36.57776 , ..., -51.153397, -43.18015 ,
        -21.366138]], dtype=float32)}


In [3]:
audio_value = dataset[1]['audio']
print(audio_value)

[ 0.00115297 -0.00249863 -0.0041079  ...  0.06591871  0.07060137
  0.058603  ]


In [188]:
audio_value = dataset[1]['audio']
audio_value2 = dataset['audio']
print(audio_value2)

[ 0.00115297 -0.00249863 -0.0041079  ...  0.06591871  0.07060137
  0.058603  ]


In [96]:
spectrogram_value = dataset[1]['spectrogram']
print(spectrogram_value)

[[-26.529797 -28.434174 -36.508366 ... -30.12642  -28.148579 -26.529797]
 [-30.04826  -28.322306 -29.266117 ... -27.803719 -27.206852 -30.04826 ]
 [-29.88448  -27.930328 -30.223663 ... -33.16832  -29.984165 -29.88448 ]
 ...
 [-37.971367 -40.22007  -52.817772 ... -36.649685 -29.14058  -37.971367]
 [-37.957653 -40.287174 -53.452892 ... -36.82059  -29.166595 -37.957653]
 [-37.97605  -40.27957  -52.881454 ... -36.796227 -29.16441  -37.97605 ]]


In [38]:
dataset = BirdDataset(data_path='../data/')

In [3]:
s=dataset[5663]

print(s)

{'species': 'Tachybaptus ruficollis', 'species_encoded': 19, 'audio': array([-0.00363688,  0.00089291,  0.00938779, ...,  0.0311252 ,
       -0.01191721, -0.0797343 ], dtype=float32), 'spectrogram': array([[-20.23129 , -22.523497, -34.74211 , ..., -36.153778, -28.631557,
        -20.23129 ],
       [-20.216858, -22.552513, -36.475227, ..., -36.464546, -28.603828,
        -20.216858],
       [-20.186378, -22.474483, -34.76468 , ..., -36.039272, -28.52197 ,
        -20.186378],
       ...,
       [-21.346306, -23.656876, -36.499725, ..., -48.630013, -42.98922 ,
        -21.346306],
       [-21.36101 , -23.672108, -36.576813, ..., -50.89184 , -43.0451  ,
        -21.36101 ],
       [-21.366138, -23.67694 , -36.57776 , ..., -51.153397, -43.18015 ,
        -21.366138]], dtype=float32)}


In [37]:
s=dataset[835]

print(s)

{'species': 'Alcedo atthis', 'species_encoded': 3, 'audio': array([ 0.04598924,  0.00918938, -0.0734762 , ...,  0.00216958,
       -0.00079494, -0.00349058], dtype=float32), 'spectrogram': '../data/spectrograms\\Alcedo atthis\\XC463509_3.npy'}


In [79]:
edad = dataset.metadata.get("species_encoded")
print(edad)


[ 0  0  0 ... 19 19 19]


In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import pyplot as plt

In [86]:
datos = dataset

In [87]:
df = pd.DataFrame(datos)

ValueError: DataFrame constructor not properly called!

In [185]:
for dia, codigos in dataset.metadata.items():
   s= dia, ":", codigos
   print(s)
if(dia=='species_encoded'):
    print(codigos)

('species', ':', ['Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceus', 'Acrocephalus arundinaceu

In [53]:
import librosa.display
import matplotlib.pyplot as plt

D = librosa.amplitude_to_db(np.abs(librosa.stft(dataset[551]['audio'])), ref=np.max)

librosa.display.specshow(D, y_axis='linear')
plt.show()

In [36]:
dataset[5663]['audio']

array([-0.00363688,  0.00089291,  0.00938779, ...,  0.0311252 ,
       -0.01191721, -0.0797343 ], dtype=float32)

In [54]:
# El espectrograma puede interpretarse como una imagen
D.shape

(1025, 41)

In [25]:
D

array([[-80., -80., -80., ..., -80., -80., -80.],
       [-80., -80., -80., ..., -80., -80., -80.],
       [-80., -80., -80., ..., -80., -80., -80.],
       ...,
       [-80., -80., -80., ..., -80., -80., -80.],
       [-80., -80., -80., ..., -80., -80., -80.],
       [-80., -80., -80., ..., -80., -80., -80.]], dtype=float32)

In [41]:
# Definimos una función para parsear nuestro conjunto de datos
import librosa
import numpy as np
def parse_dataset(dataset):
    X = []
    y = []
    try:
        for xs in range(len(dataset)):
            audio_value = dataset[xs]['audio']
            D = librosa.amplitude_to_db(np.abs(librosa.stft(audio_value)), ref=np.float32)
            X.append(D)
            X_train_prep = np.array(X).reshape((len(X), 1025*44))
           
            encoded_value = dataset[xs]['species_encoded']
            y.append(encoded_value)
    except:
        print(xs)
        audio_value = dataset[xs]['audio_name']
    return (X, y)

In [42]:
X, y = parse_dataset(dataset)

848


C:\Users\firef\AppData\Local\Temp\ipykernel_29124\2815241118.py:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train_prep = np.array(X).reshape((len(X), 1025*44))


KeyError: 'audio_name'

In [17]:
print("La longitud del conjunto de datos es: ", len(X))

La longitud del conjunto de datos es:  5664


In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [19]:
print(len(X_train))
print(len(X_test))

5380
284


In [23]:
X_train

[array([[-18.350521 , -12.9019   , -17.686996 , ..., -17.580284 ,
         -16.053581 , -13.7343025],
        [-19.822992 , -14.923164 ,  -8.293828 , ..., -14.005191 ,
         -11.086958 , -13.137215 ],
        [-21.977863 , -26.345541 ,  -8.270566 , ..., -17.9262   ,
         -13.470997 , -11.582683 ],
        ...,
        [-80.       , -80.       , -80.       , ..., -80.       ,
         -80.       , -74.81369  ],
        [-80.       , -80.       , -80.       , ..., -80.       ,
         -80.       , -74.81908  ],
        [-80.       , -80.       , -80.       , ..., -80.       ,
         -80.       , -74.82146  ]], dtype=float32),
 array([[-27.4555  , -31.27037 , -25.105068, ..., -18.007292, -16.391222,
         -20.885744],
        [-28.298033, -26.678165, -25.085846, ..., -22.373684, -20.526474,
         -22.67783 ],
        [-31.172258, -32.224667, -38.034126, ..., -37.22932 , -36.947872,
         -27.912664],
        ...,
        [-80.      , -80.      , -80.      , ..., -80.   

In [48]:
X_train_prep = np.array(X_train).reshape((len(X_train), 1025*44))
X_train_prep = np.array(X_train_prep).astype('float32') / 255
y_train_prep = np.array(y_train)

X_test_prep = np.array(X_test).reshape((len(X_test), 1025*44))
X_test_prep = np.array(X_test_prep).astype('float32') / 255
y_test_prep = np.array(y_test)

C:\Users\firef\AppData\Local\Temp\ipykernel_40436\215666264.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train_prep = np.array(X_train).reshape((len(X_train), 1025*44))


ValueError: could not broadcast input array from shape (1025,44) into shape (1025,)

In [19]:
librosa.display.specshow(X[0], y_axis='linear')
plt.show()

IndexError: tuple index out of range

In [18]:
import librosa
import numpy as np
import matplotlib.pyplot as plt

In [25]:
dataset[5662]

{'species': 'Tachybaptus ruficollis',
 'species_encoded': 19,
 'audio': array([-0.00364021, -0.00626585, -0.00459902, ...,  0.02663414,
         0.02437335,  0.00792919], dtype=float32),
 'spectrogram': array([[-26.700638, -28.975822, -39.848793, ..., -37.63483 , -29.885544,
         -26.700638],
        [-26.720387, -29.065512, -43.78183 , ..., -37.24885 , -29.892658,
         -26.720387],
        [-26.69437 , -28.98206 , -42.267727, ..., -38.1531  , -30.011356,
         -26.69437 ],
        ...,
        [-34.944424, -37.287907, -50.394806, ..., -48.554897, -40.647247,
         -34.944424],
        [-34.975903, -37.248158, -49.358833, ..., -48.434265, -40.739597,
         -34.975903],
        [-34.991947, -37.351887, -51.356464, ..., -48.73245 , -40.75494 ,
         -34.991947]], dtype=float32)}

In [20]:
X[0]

array([-0.00088778,  0.00057823,  0.00034897, ..., -0.04451931,
       -0.02608174,  0.00287091], dtype=float32)

In [9]:
for x in range(len(dataset)):
    print(dataset[1][1])

KeyError: 1

In [5]:
X = []
y = []
for x in range(len(dataset)):
    X.append(x[2])
    y.append(x[1])

 

NoBackendError: 

In [1]:
pip install git+https://github.com/librosa/librosa

Defaulting to user installation because normal site-packages is not writeable
  Cloning https://github.com/librosa/librosa to c:\users\firef\appdata\local\temp\pip-req-build-csy4v6eg
  Resolved https://github.com/librosa/librosa to commit c800e74f6a6ec5c27e0fa978d7355943cce04359
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Note: you may need to restart the kernel to use updated packages.


  Running command git clone --filter=blob:none --quiet https://github.com/librosa/librosa 'C:\Users\firef\AppData\Local\Temp\pip-req-build-csy4v6eg'
  Running command git submodule update --init --recursive -q


hola
